enum Creatures
{
    CREATURE_ARGALOTH  = 47120,
    CREATURE_OCCUTHAR  = 52363,
	CREATURE_ALIZABAL  = 55869,
};

enum Data
{
    DATA_ARGALOTH,
    DATA_OCCUTHAR,
	DATA_ALIZABAL,
    MAX_ENCOUNTER
};