DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_CONTACT_LIST');
INSERT INTO `opcodes` VALUES ('CMSG_CONTACT_LIST', 0x4534, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_CONTACT_LIST');
INSERT INTO `opcodes` VALUES ('SMSG_CONTACT_LIST', 0x6017, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_ADD_FRIEND');
INSERT INTO `opcodes` VALUES ('CMSG_ADD_FRIEND', 0x6527, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_ADD_IGNORE');
INSERT INTO `opcodes` VALUES ('CMSG_ADD_IGNORE', 0x4726, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_DEL_FRIEND');
INSERT INTO `opcodes` VALUES ('CMSG_DEL_FRIEND', 0x6A15, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_DEL_IGNORE');
INSERT INTO `opcodes` VALUES ('CMSG_DEL_IGNORE', 0x6D26, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_FRIEND_STATUS');
INSERT INTO `opcodes` VALUES ('SMSG_FRIEND_STATUS', 0x0717, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_SET_CONTACT_NOTES');
INSERT INTO `opcodes` VALUES ('CMSG_SET_CONTACT_NOTES', 0x6135, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_WHO');
INSERT INTO `opcodes` VALUES ('CMSG_WHO', 0x6C15, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_WHO');
INSERT INTO `opcodes` VALUES ('SMSG_WHO', 0x6907, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_WHOIS');
INSERT INTO `opcodes` VALUES ('CMSG_WHOIS', 0x6B05, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_GROUP_INVITE');
INSERT INTO `opcodes` VALUES ('CMSG_GROUP_INVITE', 0x513, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_PLAYED_TIME');
INSERT INTO `opcodes` VALUES ('SMSG_PLAYED_TIME', 0x6037, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_PARTY_COMMAND_RESULT');
INSERT INTO `opcodes` VALUES ('SMSG_PARTY_COMMAND_RESULT', 0x6E07, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_GROUP_LIST');
INSERT INTO `opcodes` VALUES ('SMSG_GROUP_LIST', 0x4C24, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_GROUP_SET_LEADER');
INSERT INTO `opcodes` VALUES ('CMSG_GROUP_SET_LEADER', 0x4C17, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_GROUP_SET_LEADER');
INSERT INTO `opcodes` VALUES ('SMSG_GROUP_SET_LEADER', 0x0526, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_WORLD_STATE_UI_TIMER_UPDATE');
INSERT INTO `opcodes` VALUES ('CMSG_WORLD_STATE_UI_TIMER_UPDATE', 0x4605, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_WORLD_STATE_UI_TIMER_UPDATE');
INSERT INTO `opcodes` VALUES ('SMSG_WORLD_STATE_UI_TIMER_UPDATE', 0x4A14, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_FLIGHT_SPLINE_SYNC');
INSERT INTO `opcodes` VALUES ('SMSG_FLIGHT_SPLINE_SYNC', 0x0924, '15595', '15595');

DELETE FROM `opcodes` WHERE `OpcodeName` IN ('SMSG_EMOTE');
INSERT INTO `opcodes` VALUES ('SMSG_EMOTE', 0x0A34, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_EMOTE');
INSERT INTO `opcodes` VALUES ('CMSG_EMOTE', 0x4C26, '15595', '15595');
DELETE FROM `opcodes` WHERE `OpcodeName` IN ('CMSG_TEXT_EMOTE');
INSERT INTO `opcodes` VALUES ('CMSG_TEXT_EMOTE', 0x2E24, '15595', '15595');
