#!/bin/bash
# Massive Network Game Object Server
# autorestart Script

while :
do
	echo "StrawberryWorld daemon restarted"
	echo `date` >> crash.log &
	./strawberryworld | tail -n 20 >> crash.log
	echo " " >> crash.log &
	pid=`ps ax | awk '($5 ~ /strawberryworld/) { print $1 }'`
	wait $pid
        echo `date` ", StrawberryWorld daemon crashed and restarted." >> serverlog
done
